### ISSUE TITLE
Issues working right with 11.1

### ISSUE THREAD

**Issue by DinoNuggets2** [joker-119/LogArchiver#2]
It won't clear logs right with 11.1. I haven't checked it out fully, so I could be wrong, but it is enabled for me and a lot of logs are staying in the ServerLogs and LocalAdminLogs files.

**Comment by joker-119** [comment]
You likely have the file paths in the config incorrect, the plugin is working fine.

**Comment by DinoNuggets2** [comment]
Sorry, I was wrong, it was working. When I installed the 4.00 EXILED it changed my storage and I've been reinstalling plugins, I just got mixed up.
